version: "3.8"

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prasanth@1801
      POSTGRES_DB: QuizAppDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: quizappapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=QuizAppDB;Username=postgres;Password=Prasanth@1801
    ports:
      - "5038:8080"
    depends_on:
      - db
volumes:
  pgdata:
    driver: local

